/**
 * Daftar rute untuk audit visual (screenshots.mjs set "audit") dan simulasi
 * UI penuh (ui-sim.mjs). Satu sumber kebenaran: rute baru cukup ditambah di
 * sini agar tercakup keduanya. Format: [path, nama-berkas].
 */
export const AUDIT_ROUTES = [
  ["/", "landing"],
  ["/masuk", "masuk"],
  ["/daftar", "daftar"],
  ["/panduan", "panduan-indeks"],
  ["/panduan/pos", "panduan-modul"],
  ["/app", "dashboard"],
  ["/app/pos", "pos"],
  ["/app/penjualan", "penjualan"],
  ["/app/pesanan-penjualan", "pesanan-penjualan"],
  ["/app/pembelian", "pembelian"],
  ["/app/pengadaan", "pengadaan"],
  ["/app/persetujuan", "persetujuan"],
  ["/app/stok", "stok"],
  ["/app/master/produk", "produk"],
  ["/app/master/kontak", "kontak"],
  ["/app/master/gudang", "gudang"],
  ["/app/crm/leads", "crm-leads"],
  ["/app/crm/penawaran", "crm-penawaran"],
  ["/app/helpdesk", "helpdesk"],
  ["/app/keuangan/catat", "catat"],
  ["/app/keuangan/kas-bank", "kas-bank"],
  ["/app/keuangan/akun", "akun"],
  ["/app/keuangan/jurnal", "jurnal"],
  ["/app/keuangan/buku-besar", "buku-besar"],
  ["/app/keuangan/neraca-saldo", "neraca-saldo"],
  ["/app/keuangan/laba-rugi", "laba-rugi"],
  ["/app/keuangan/neraca", "neraca"],
  ["/app/keuangan/umur-tagihan", "umur-tagihan"],
  ["/app/keuangan/arus-kas", "arus-kas"],
  ["/app/keuangan/e-faktur", "e-faktur"],
  ["/app/keuangan/pajak", "pajak"],
  ["/app/keuangan/anggaran", "anggaran"],
  ["/app/keuangan/dimensi", "dimensi"],
  ["/app/keuangan/aset", "aset"],
  ["/app/keuangan/kurs", "kurs"],
  ["/app/laporan/penjualan", "laporan-penjualan"],
  ["/app/hr/penggajian", "penggajian"],
  ["/app/hr/absensi", "absensi"],
  ["/app/proyek", "proyek"],
  ["/app/kontrak", "kontrak"],
  ["/app/konsolidasi", "konsolidasi"],
  ["/app/manufaktur", "manufaktur"],
  ["/app/maintenance", "maintenance"],
  ["/app/migrasi", "migrasi"],
  ["/app/pengaturan", "pengaturan"],
];
